site_name: Mantis
theme: readthedocs
pages:
  - Home: index.md
  - Quick Start: quick_start.md
  - Advanced Configuration: advanced_configuration.md
  - Private Network Setup: private_network_setup.md
  - Misc: misc.md
